apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-creds
      key: creds
  endpoint:
    url:
      type: Static
      static: http://floci.floci.svc.cluster.local:4566
    hostnameImmutable: true
    services:
      - ec2
      - iam
      - eks
      - rds
      - dynamodb
      - sqs
      - sns
      - s3
  skip_credentials_validation: true
  skip_metadata_api_check: true
  skip_requesting_account_id: true
  skip_region_validation: true
