apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: floci
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: REPO_URL_PLACEHOLDER
    targetRevision: HEAD
    path: floci
  destination:
    server: https://kubernetes.default.svc
    namespace: floci
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
